"""Text chunking for RAG."""

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document

from mediagent_lite.config.settings import get_settings


def get_chunker() -> RecursiveCharacterTextSplitter:
    """Return configured text splitter."""
    settings = get_settings()
    return RecursiveCharacterTextSplitter(
        chunk_size=settings.chunk_size,
        chunk_overlap=settings.chunk_overlap,
        separators=["\n\n", "\n", ". ", " ", ""],
    )


def chunk_document(text: str, metadata: dict[str, str]) -> list[Document]:
    """Chunk text and attach metadata."""
    chunker = get_chunker()
    chunks = chunker.split_text(text)
    
    docs = []
    for i, chunk in enumerate(chunks):
        # Create a deep copy of metadata so we don't mutate the original
        chunk_metadata = dict(metadata)
        chunk_metadata["chunk_index"] = i
        # The ID will be generated by Qdrant, but we store source details here
        docs.append(Document(page_content=chunk, metadata=chunk_metadata))
        
    return docs
